### ISSUE TITLE
Hackshop project couldn't be created

### ISSUE THREAD

**Issue by BretFisher** [waffleio/hackshop#10]
Hey Waffle team!

We were planning to use the Hackshop playbook today Fri/Sat for a Norfolk Hackathon, but I was testing repo creation in order to do a demo and got this, thoughts?:

<img width="1040" alt="hackshop___waffle_io" src="https://cloud.githubusercontent.com/assets/792287/10686514/f1d24932-7932-11e5-8762-0063fa6c75d0.png">

**Comment by BretFisher** [comment]
Also confirmed that others have this issue.

**Comment by ashumz** [comment]
Hi @bretfisher - we're looking into this!

**Comment by homeyer** [comment]
@BretFisher - I just updated hackshop to show the specific error when it fails. Can you try again and tell us what you see?

And, the first thing that comes to mind is that `dudebro` already exists; hackshop creates a new repo, so you can't re-use an existing one. Just a guess though, without seeing the specific error.

**Comment by ashumz** [comment]
Hi @BretFisher - any chance you could hop on a Hangout to talk quickly about your event? I am able to replicate the error most of the time but would like to hear what you're seeing for the error as well. If we can't get it fixed before your event, I'd be happy to help you with using the content of the cards (can put them into slides if you have a projector, and just have attendees use Waffle and create cards as necessary/as they go.) 

Will your event be making use of a lean canvas? That's a big part of it -- and you can use the lean canvas to focus the content around (which I can help out with -- just shoot me a note at ashley@waffle.io and we can hop on a Hangout if it makes sense.) 

Sorry you ran into this! 

Ashley

**Comment by ashumz** [comment]
Hey @BretFisher - I was able to create a couple of projects just now. I replicated the failure a couple of times earlier today, but things seem to be running smoothly now. You might try creating a project in an incognito window in the case that there is an caching of an expire Waffle oauth token -- but that shouldn't be something new users run into. 

Give that a shot and let me know. Still open to hopping on a Hangout and helping out however I can. 

Best, 

Ashley

**Comment by ashumz** [comment]
Just did several more tests and everything is working currently @BretFisher. If the project fails, I'd suggest trying it again  - might be a timeout or something intermittent at this point (and as @homeyer mentioned, make sure the project doesn't exist yet.) The only issue I am able to replicate at this point that you might run into is an expired authentication token which can be fixed by clearing browsing history or creating the project in an incognito window. 

Let me know if you have any additional questions or issues! Sorry for the trouble. 

Ashley

**Comment by ashumz** [comment]
And let us know how the hackathon goes or if you have feedback on the playbook. We're actively looking for feedback to improve it. :)

**Comment by BretFisher** [comment]
Thanks team, sorry we're in the middle of day one of the hackathon. I wasn't able to plan ahead for using lean canvas, and many of the teams came with their own repo's already created so that would have been a blocker as well. A feature request would definitely be plugging in the issues to an existing repo.  Code for Hampton Roads is playing a small role in this [hackathon run by our partner](http://hackathon.dominionenterprises.com) so I hope to use it more extensively (and more forethought) in February for Code Across

**Comment by BretFisher** [comment]
I was able to create a new repo now, thanks @ashumz and @homeyer
