### ISSUE TITLE
Allow user to select which organization the repository will be created in.

### ISSUE THREAD

**Issue by zmon** [waffleio/hackshop#24]
I am trying to create a 'organizers' site for Code Across.  It only allows me to put it in my personal GitHub account.  I need to have in CodeForKC organization.  

This would not be an issue, but when I try to transfer it to CodeForKC, the Milestones do not transfer it.

**Comment by ashumz** [comment]
Hi @zmon, 
Happy to hear you're creating a board for Code Across. :) We may add this capability eventually, but for now the best workaround is to move the board to the CodeForKC organization through transferring it. 

I tried this on my end, and it looks like all of the labels transferred over to the new repo.
When you did this, did labels not transfer over? Did you transfer the repo in Settings like this?: 
![screen shot 2016-02-03 at 12 17 09 pm](https://cloud.githubusercontent.com/assets/100216/12793973/27ea16ec-ca70-11e5-8dc5-6e1ba975eb63.png)

One somewhat unrelated note: we just updated our Organizer cards to have check lists and additional information, so it might be worthwhile to create a new board, actually! :) 

Keep me posted on what you're seeing. Eventually we'll look at allowing you to create the board directly in the org (and actually, we're working on a bot right now for organizers that works with Slack - would love your thoughts on if this is useful for your event potentially!: https://waffle.io/waffleio/waffle.io/cards/56b2542c81130f0e00c753b5)

**Comment by mckaydavis** [comment]
In a similar vein, I would like the ability to select an already existing repository.  CodeforHawaii already has a repo specifically to track issues via waffle.io that we used for planning CodeAcross w/ a new milestone.

It would be great if I could specify an existing repo (it would be created if it doesn't exist), specify an event name, and hackshop would batch create issues for that specific event/milestone.
